### ISSUE TITLE
Typos in the Win10_1909_VDI_Optimize.ps1

### ISSUE THREAD

**Issue by 2Deep2Dive** [TheVDIGuys/Windows_10_VDI_Optimize#15]
Hi,
There is a typo in the script under the Disable Windows Traces region
 Win10_1093_ServicesAutologgersDisable.txt
should be 
Win10_1909_ServicesAutologgersDisable.txt

**Comment by tmmuessig** [comment]
Thanks 2Deep2Dive for catching that.  Issue has been corrected.

**Comment by 2Deep2Dive** [comment]
Hi Tim,

Thank for correcting the issue, one more thing if I may
I was testing the script today and the following packages must be added to the Win10_1909_AppxPackages.txt so the system can be Syspreped

Microsoft.DesktopAppInstaller
Microsoft.HEIFImageExtention
Microsoft.Microsoft3DViewer
Microsoft.MixedReality.Portal
Microsoft.ScreenSketch
Microsoft.VP9VideoExtentions
Microsoft.WebMediaExtentions
Microsoft.WebImageExtention
Microsoft.WindowsSoundRecorder

Cheers,
Mohamed
