### ISSUE TITLE
Typo in Win10_1909_DefaultUserSettings.txt

### ISSUE THREAD

**Issue by kevinpagliarulo** [TheVDIGuys/Windows_10_VDI_Optimize#16]
Missing double quote on line 24
add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications\Microsoft.Windows.Photos_8wekyb3d8bbwe" /v Disabled /t REG_DWORD /d 1 /f

**Comment by tmmuessig** [comment]
Resolved issue
