### ISSUE TITLE
Missing Apps from Win10_1909_AppxPackages.txt

### ISSUE THREAD

**Issue by 2Deep2Dive** [TheVDIGuys/Windows_10_VDI_Optimize#17]
Hi Tim,

The following apps must be added to the Win10_1909_AppxPackages.txt, so they are removed via the script, if not added sysprep will fail and generate an error

Microsoft.DesktopAppInstaller
Microsoft.HEIFImageExtension
Microsoft.Microsoft3DViewer
Microsoft.MixedReality.Portal
Microsoft.ScreenSketch
Microsoft.VP9VideoExtensions
Microsoft.WebMediaExtensions
Microsoft.WebpImageExtension
Microsoft.WindowsSoundRecorder

Cheers,
Mohamed

**Comment by tmmuessig** [comment]
Hi Mohamed,

As of right now, those are not supported for removal, but if you need to, you can add them to your AppxPackages.txt file for your own use.

Thanks,
Tim
