### ISSUE TITLE
Windows Update Crash 

### ISSUE THREAD

**Issue by gotsquats** [TheVDIGuys/Windows_10_VDI_Optimize#18]
Hi, we are testing this ps1 script as is and its working well apart form breaking windows update.  After running the script, windows update screen stays stuck and all you see is blue dots trickling across the screen and no settings appear in the Windows Update.

**Comment by tmmuessig** [comment]
Hello.  Disabling of Windows Update in this is intentional.  We suggest that you run Windows Update before the script is run, but it can be re-enabled if you choose to do so.

**Comment by gotsquats** [comment]
Hi Tim

Thanks for your reply, after running the script, we then tried to the
following to get windows working but its the same behavior, the windows
update screen rolls the blue dots and you dont see any information, just a
white screen.


   1. Disabled Windows Automatic Updates
   2. Stopped Windows Update service
   3. Stopped BITS service
   4. Emptied the C:\Windows\SoftwareDistribution folder
   5. Started the Windows Update service
   6. Started BITS service
   7. Enabled Windows Automatic Updates
   8. Launched a check for Windows Updates
   9. white screen with blue dots trickling.

i suspect maybe one of the other services int he disable services text file
might be causing this issue but BITS ans WU service should be the only
dependencies for properly running windows update.

i'll do some more testing and thanks again for replying.

Dave

**Comment by tmmuessig** [comment]
@gotsquats - We have created a new folder that contains the necessary settings to enable Windows Update (1909_WindowsUpdateEnabled).  This should solve your immediate issues with regards to Windows Update no working.  Additionally, we have updated the ReadMe.

**Comment by gotsquats** [comment]
Thank you for the update

i've downloaded a fresh copy of all the files the 1909_WindowsUpdateEnabled
repository for testing and to review the files.  A few observations:

# IMPORTANT ISSUE (01/27/2020)
A new issue was discovered recently regarding the *'CDPSvc*' (*CDPSvc is
still part of the Win10_1909_ServicesDisable.txt* file). If that service is
disabled, and
a new user logs on to the computer then opens 'System Settings' to view
display settings,
'SystemSettings.exe' will crash and log an error to the event log with code
"fatal app exit".
We removed the entry 'CDPSvc' from 'Win10_1909_ServicesDisable.txt' as a
result.

We tested the 1909_WindowsUpdateEnabled script and its the same issue.
after running the script and rebooting no info displayed under windows
update and dots trickle ontop of the screen.
