### ISSUE TITLE
No able to login through RDP after running the script

### ISSUE THREAD

**Issue by Perh0rd** [TheVDIGuys/Windows_10_VDI_Optimize#19]
Hi,

Just run the script and I cannot logon through RDP into the windows machine in a labo env.

Any idea?

Thank you.

**Comment by sandude-ms** [comment]
Hello,

Did you get this resolved?

Thanks,

Robert Smith

**Comment by Perh0rd** [comment]
Hi,

No I just abandoned….



[cid:yes_3da80858-3439-44b5-9634-b44e2aaa4a11.jpg]
  Paul Erhard
   CTO

   T : +1-888-264-7159
   Website : https://www.xpedigo.com

**Comment by resartiia** [comment]
Hi 

Does anybody have same issue? I was able to reproduce it with Windows 10 1909 in WVD environment.  After you execute the script and reboot, it's not going to allow RDP. Hard reboot resolves the issue.
