### ISSUE TITLE
AppxPackages.json - Duplicate entry at the bottom

### ISSUE THREAD

**Issue by cjpalmer** [TheVDIGuys/Windows_10_VDI_Optimize#25]
In the JSON file, there is an entry at bottom for Microsoft.OneConnect which has the guts of Microsoft.Microsoft3dViewer but the name of the first item on the page. This entry needs to be removed from the .JSON file (and/or script that generates the JSON file needs to be updated to not duplicate this entry in the future)

**Comment by cjpalmer** [comment]
I would be happy to do a pull request with a fix for this issue in the AppxPackages.json file. I was looking at the Build_JSON_Files.ps1 file to see about updating it to generate this file correctly and it seems that file is significantly removed from the current 2004 json and txt files.

**Comment by tmmuessig** [comment]
Duplicate entries have been removed
