### ISSUE TITLE
DefaultUserSettings.txt has duplicate entries

### ISSUE THREAD

**Issue by cjpalmer** [TheVDIGuys/Windows_10_VDI_Optimize#26]
At the bottom of the file just before 'Unload HKLM\Temp, the same line is repeated three times:

add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f
add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f
add "HKLM\Temp\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f

I edited mine before I ran it so that this entry only appeared once and then I checked my registry afterwards and the single entry was successful in creating the required registry key/value.

**Comment by cjpalmer** [comment]
I would be happy to do a pull request with a fix for this issue in the DefaultUserSettings.txt file. I was looking at the Build_JSON_Files.ps1 file to see about updating it to generate this file correctly and it seems that file is significantly removed from the current 2004 json and txt files.

**Comment by tmmuessig** [comment]
Duplicates removed.
