### ISSUE TITLE
Win10_VirtualDesktop_Optimize.ps1 line 158 when executing AutoLoggers.json gets an error

### ISSUE THREAD

**Issue by cjpalmer** [TheVDIGuys/Windows_10_VDI_Optimize#27]
When running the script on my clean Windows 10 Enterprise Multi-session 2004 with Microsoft 365 WVD image, I got the following error:

New-ItemProperty : Requested registry access is not allowed.
At C:\Windows_10_VDI_Optimize\Win10_VirtualDesktop_Optimize.ps1:158 char:9

This failure occurred when processing the following entry from Autologgers.json:
HKLM:\\SYSTEM\\CurrentControlSet\\Control\\WMI\\Autologger\\RadioMgr\\
I went to the specified registry location using the GUI and the Start value is already there with a value of 1. I am not sure if it was already there before I ran the script and haven't had a change to spin up another image to test with yet. In the GUI, I am unable to change the Start value to 0. When I click OK after changing the value, I get "Cannot edit Start: Error writing the value's new contents." error. 
Checking the Permissions for the RadioMgr key and comparing it to DiagLog, RadioMgr seems to be locked down to only TrustedInstallers being able to change settings. I am not sure if this is a change on 2004 from 1909 (actually, on 1909, it is the same way) or some previous version, but it seems without extraordinary action, the script cannot set the Start value for RadioMgr.

**Comment by tmmuessig** [comment]
Currently investigating this

**Comment by TheVDIGuys** [comment]
We have moved to a new repository.  All updates to the code can now be found at the following location: https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool
