### ISSUE TITLE
Win10 Ent 2004 Outlook / Domain Join GUI

### ISSUE THREAD

**Issue by journeym** [TheVDIGuys/Windows_10_VDI_Optimize#28]
Seems that after applying some of the listed gpo optimizations on my 2004 VDI machines wont work the following fuctionality:
1. Domain Join using GUI (Control Panel > System > etc)
2. Outlook autodiscover using GUI, for example, first time connecting to exchange, and further on. (Though autodiscover test works fine, all green).
Problems were gone after i deleted registry.pol in system32\GroupPolicy\Machine
I have exported it using lgpo before deleting, maybe someone more experienced can point me out to exact values that can cause this.
Lgpo export https://pastebin.com/zXa19Puc

**Comment by tmmuessig** [comment]
Investigating

**Comment by TheVDIGuys** [comment]
We have moved to a new repository.  All updates to the code can now be found at the following location: https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool
