### ISSUE TITLE
Win 1909 - Start Menu Search Issues

### ISSUE THREAD

**Issue by Misterjohnson87** [TheVDIGuys/Windows_10_VDI_Optimize#30]
Hey,

We're using the 1909 script to optimise WVD but we've noticed that after building the machine that searching in the start menu doesn't work. It eventually starts to respond and work after some time. 

Not sure if this is something in the script? We've renabled Windows Search and  can't find any other issues.

Thanks

**Comment by TheVDIGuys** [comment]
This is currently being investigated, but moving forward we are utilizing a new repository where all changes and updates will be made available, including this issue once a solution is found.  That GitHub location is: https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool
