### ISSUE TITLE
Breaking Brightness Level on Laptop - 1909

### ISSUE THREAD

**Issue by GokulG07** [TheVDIGuys/Windows_10_VDI_Optimize#5]
Disabling Power(Service) is breaking Brightness level, Stuck on Max Brightness On Laptop.

**Comment by tmmuessig** [comment]
Virtual machines have virtually no influence on power properties. Changing power settings have no impact, therefore this service is likely not needed.

**NOTE**: If using this script on a physical machine, this setting should not be changed from default and removed from the input file.

The official documentation will be updated to reflect this better.
